Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-11, with the labels that each got.

#192 Display 0 balance when wallet not connected
  src/models/history/historyManager.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/PageWallets.qml
Labels: bug, stdev, wallet

#197 Fix transactions
  src/coin/skycoin/models/api.go
  src/coin/skycoin/models/main.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/models/walletsManager.go
  src/ui/PageSend.qml
Labels: sign_api, skyfiber, stdev, wallet, wip

#194 Fix decrypt and edit wallet buttons
  src/models/walletsManager.go
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogEditWallet.qml
Labels: gui, stdev, wallet, wip

#201 Fix filter list in history page
  src/models/history/historyManager.go
  src/ui/Delegates/HistoryFilterListDelegate.qml
Labels: account, stdev, wip

#206 Blank page showed when there are not created wallets
  src/ui/GeneralStackView.qml
  src/ui/PageCreateLoadWallet.qml
Labels: stdev, wallet, wip

#221 [core] [sky] refs #189 - Internal skytypes package
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/skytypes/api.go
  src/coin/skycoin/skytypes/wallet.go
  src/core/api.go
Labels: skyfiber, stdev, wip

#224 [sky] [core] [models] fixes #190 - Support for multiple coins in Wallet.Transfer
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/wallet.go
  src/core/coin.go
  src/core/storage.go
  src/core/wallet.go
  src/models/walletsManager.go
  src/util/cipher.go
  src/util/coin.go
  src/util/storage.go
Labels: core, qml_models, skyfiber, stdev, wip

#223 Fixes #219 Add target to update release resources
  Makefile
  qml.qrc
  setup_release.sh
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/HistoryFilterListDelegate.qml
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/PanelItem.qml
  src/ui/Delegates/TransactionAddressDelegate.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogAboutQt.qml
  src/ui/Dialogs/DialogAddLoadWallet.qml
  src/ui/Dialogs/DialogGetPassword.qml
  src/ui/Dialogs/DialogQR.qml
  src/ui/GeneralStackView.qml
  src/ui/Networking.qml
  src/ui/Outputs.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/Utils/QRCode.qml
  src/ui/Utils/qqr.js
  src/ui/main.qml
Labels: ci, os-darwin, os-windows

#229 Backend unit tests for Skyfiber wallet models.
  .gitignore
  Makefile
  src/coin/skycoin/main_test.go
  src/coin/skycoin/models/account_test.go
  src/coin/skycoin/models/blockchain_test.go
  src/coin/skycoin/models/network_test.go
  src/coin/skycoin/models/skyapi_mock_test.go
  src/coin/skycoin/models/wallet_test.go
  src/core/network.go
Labels: core, stdev, wip

#160 Fixes #124 - Need asynchronous network operations and a busy indicator in the UI
  src/models/addressesModel.go
  src/models/blockchainModels.go
  src/models/modelWallets.go
  src/models/pending/PendingModel.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/Blockchain.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Networking.qml
  src/ui/Outputs.qml
  src/ui/PageWallets.qml
  src/ui/PendingTransactions.qml
Labels: enhancement, good first issue, gui, stdev, wip

#226 Fixes#196 Display balance in send pages (Simple and Advance)
  src/models/modelOutputs.go
  src/ui/Dialogs/DialogQR.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/SubPageSendSimple.qml
Labels: enhancement, good first issue, gui, needs graphics, stdev

#180 Fix scroll issues
  .github/pull_request_template.md
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/HistoryFilterListDelegate.qml
  src/ui/Delegates/HistoryListDelegate.qml
  src/ui/Dialogs/DialogAboutLicense.qml
  src/ui/PendingTransactions.qml
  src/ui/SubPageSendAdvanced.qml
Labels: bug, gui, stdev, wip

#250 Fixes #136 - Backend unit tests
  src/coin/skycoin/models/account_test.go
  src/coin/skycoin/models/api.go
  src/coin/skycoin/models/blockchain_test.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/coin_test.go
  src/coin/skycoin/models/network_test.go
  src/coin/skycoin/models/networking.go
  src/coin/skycoin/models/sky_test.go
  src/coin/skycoin/models/skyapi_mock_test.go
  src/coin/skycoin/models/wallet_test.go
Labels: core, skyfiber, stdev, wip

#251 [release] Update release script for MacOS
  .travis/setup_release.sh
  Makefile
  setup_release.sh
Labels: ci, os-darwin

#254 fixes #234 - Global altcoin manager deals with signers
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  Makefile
  README.md
  src/coin/mocks/Address.go
  src/coin/mocks/AddressIterator.go
  src/coin/mocks/AltcoinManager.go
  src/coin/mocks/AltcoinPlugin.go
  src/coin/mocks/Block.go
  src/coin/mocks/BlockchainStatus.go
  src/coin/mocks/CryptoAccount.go
  src/coin/mocks/KeyValueStorage.go
  src/coin/mocks/MultiPool.go
  src/coin/mocks/MultiPoolSection.go
  src/coin/mocks/PEX.go
  src/coin/mocks/PexNode.go
  src/coin/mocks/PexNodeIterator.go
  src/coin/mocks/PexNodeSet.go
  src/coin/mocks/PooledObjectFactory.go
  src/coin/mocks/SeedGenerator.go
  src/coin/mocks/Transaction.go
  src/coin/mocks/TransactionInput.go
  src/coin/mocks/TransactionInputIterator.go
  src/coin/mocks/TransactionIterator.go
  src/coin/mocks/TransactionOutput.go
  src/coin/mocks/TransactionOutputIterator.go
  src/coin/mocks/TxnSigner.go
  src/coin/mocks/TxnSignerIterator.go
  src/coin/mocks/Wallet.go
  src/coin/mocks/WalletEnv.go
  src/coin/mocks/WalletIterator.go
  src/coin/mocks/WalletSet.go
  src/coin/mocks/WalletStorage.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/models/wallet_test.go
  src/coin/skycoin/skytypes/wallet.go
  src/core/cipher.go
  src/core/main.go
  src/core/wallet.go
  src/main/plugin.go
  src/main/sign.go
  src/models/history/historyManager.go
  src/models/modelWallets.go
  src/models/pending/PendingModel.go
  src/models/walletsManager.go
  src/util/pluginutil.go
  src/util/sign.go
  src/util/sign_test.go
  src/util/signutil/sign.go
Labels: core, qml_models, sign_api, skyfiber, stdev, wallet, wip

#161 Fixes #34 and #37 - An About Dialog & Set an application icon
  .gitignore
  .travis.yml
  Makefile
  README.md
  images.qrc
  main.go
  resources/images/icons/appIcon.ico
  resources/images/icons/appIcon.png
  resources/images/icons/appIcon/appIcon-fiber-shadow.png
  resources/images/icons/appIcon/appIcon-fiber.png
  resources/images/icons/appIcon/appIcon-wallet-shadow.png
  resources/images/icons/appIcon/appIcon-wallet.png
  resources/images/icons/appIcon/appIcon.icns
  resources/images/icons/appIcon/appIcon.ico
  resources/images/icons/appIcon/appIcon.png
  resources/images/icons/appIcon/splash.png
  resources/platform/darwin/Info.plist
  resources/platform/windows/winResources.rc
  src/core/network.go
  src/ui/CustomMenuBar.qml
  src/ui/Dialogs/DialogAbout.qml
  src/ui/Dialogs/MsgDialog.qml
Labels: ci, enhancement, gui, stdev

#259 refs #256 - Add project badges in README.md
  CONTRIBUTING.md
  README.md
Labels: ci
