Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-09, with the labels that each got.

#118 Unify skyfiber connection pool code
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/util/connection.go
Labels: skyfiber, stdev, wip

#95 Fixes #48 Add networking to wallet
  main.go
  src/coin/skycoin/models/networking.go
  src/core/network.go
  src/models/networking.go
  src/models/networkingManager.go
  src/models/networkingModel.go
  src/models/wallet.go
  src/ui/Delegates/NetworkingListDelegate.qml
  src/ui/Networking.qml
Labels: core, pex, skyfiber, stdev, wallet, wip

#110 Fix wallet and addresses balance and link buttons in wallet Pages to actions in the backend
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/wallet.go
  src/models/addressesModel.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/ControlGenerateSeed.qml
  src/ui/CreateLoadWallet.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogAddAddresses.qml
  src/ui/Dialogs/DialogAddLoadWallet.qml
  src/ui/Dialogs/DialogEditWallet.qml
  src/ui/Dialogs/DialogGetPassword.qml
  src/ui/Dialogs/RequestPasswordDialog.qml
  src/ui/GeneralStackView.qml
  src/ui/PageWallets.qml
  src/ui/main.qml
Labels: skyfiber, stdev, wip

#109 Backend to manage outputs
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/wallet.go
  src/models/Outputs.go
  src/models/modelAddresses.go
  src/models/modelOutputs.go
  src/models/modelWallets.go
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/OutputsListDelegate.qml
  src/ui/Outputs.qml
  src/util/util.go
Labels: core, skyfiber, stdev, wallet, wip

#131 Starting point of #129 - A Dark (night) theme
  images.qrc
  resources/images/icons/moon.svg
  resources/images/icons/sun.svg
  src/ui/CustomMenuBar.qml
Labels: enhancement, gui, stdev

#130 Fixes #128 - Generic Dialogs to set and request passwords
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogGetPassword.qml
  src/ui/Dialogs/DialogSetPassword.qml
  src/ui/Dialogs/RequestPasswordDialog.qml
  src/ui/PasswordRequester.qml
Labels: enhancement, gui, stdev

#127 Fixes #121- Change Behavior of Advanced Sent Page
  src/ui/SubPageSendAdvanced.qml
Labels: enhancement, gui, stdev

#132 Update of #129 - A dark (night) theme
  src/ui/ControlCustomSwitch.qml
  src/ui/CustomHeader.qml
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/MenuThemeAccent.qml
  src/ui/PageCreateLoadWallet.qml
  src/ui/PageSend.qml
  src/ui/PageWallets.qml
  src/ui/main.qml
Labels: gui, stdev

#134 Fixes #133 - UI to select the change address
  src/ui/CustomComboBoxDropDown.qml
  src/ui/Dialogs/DialogSelectAddressByWallet.qml
  src/ui/SubPageSendAdvanced.qml
Labels: enhancement, gui, stdev

#103 Fixes #49 backend to manage pending transactions
  main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/network.go
  src/core/account.go
  src/core/coin.go
  src/core/network.go
  src/models/addressesModel.go
  src/models/blockchainModels.go
  src/models/history/historyManager.go
  src/models/modelWallets.go
  src/models/pending/Pending.go
  src/models/pending/PendingModel.go
  src/models/walletsManager.go
  src/ui/Delegates/PendingTransactionsDelegate.qml
  src/ui/PendingTransactions.qml
  src/util/pluginutil.go
  src/util/util.go
Labels: pex, skyfiber, stdev, wip

#146 Fixes #142 - Transform value receivers into pointer receivers
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/networking.go
  src/coin/skycoin/models/wallet.go
  src/models/blockchainModels.go
Labels: skyfiber, stdev, wip

#151 Fixes #133 - UI to select the change address
  src/ui/MenuThemeAccent.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/main.qml
Labels: bug, gui

#145 Fixes #140 - CoinHours and calculatedHours conflict.
  src/coin/skycoin/main.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/params.go
  src/coin/skycoin/params/params.go
  src/core/coin.go
  src/models/addressesModel.go
  src/models/history/historyManager.go
  src/models/modelWallets.go
  src/models/walletsManager.go
  src/util/util.go
Labels: core, gui, qml_models, stdev, wip

#154 Fixes #38 - Set a license
  LICENSE.GPLv3
  images.qrc
  resources/images/icons/license.svg
  src/ui/CustomMenuBar.qml
  src/ui/Dialogs/DialogAboutLicense.qml
  src/ui/main.qml
Labels: enhancement, gui, stdev

#155 Fixes UI related issues of #150 - Spend in single transaction outputs managed by multiple wallets
  src/ui/Dialogs/DialogSelectAddressByWallet.qml
  src/ui/SubPageSendAdvanced.qml
Labels: enhancement, gui, stdev
