Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-08, with the labels that each got.

#98 Fixes issue #97 - Turn QR code images into buttons
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/HistoryListDelegate.qml
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Dialogs/DialogQR.qml
  src/ui/SubPageSendSimple.qml
  src/ui/ToolButtonQR.qml
  src/ui/main.qml
Labels: bug, good first issue, gui, stdev

#100 Fixes issue #99 - Custom dropdown UI for combo boxes that show addresses
  src/ui/CustomComboBoxDropDown.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/SubPageSendSimple.qml
Labels: enhancement, good first issue, gui, stdev

#88 Issue #43 backend to manage list of wallets
  .travis.yml
  Makefile
  main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/wallet.go
  src/core/cipher.go
  src/core/wallet.go
  src/models/addressesModel.go
  src/models/wallet.go
  src/models/wallets.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/Blockchain.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/GeneralStackView.qml
  src/ui/Networking.qml
  src/ui/PageWallets.qml
  src/ui/main.qml
  src/util/connection.go
  src/util/util.go
Labels: core, skyfiber, stdev, wip

#105 fixes #2 GitHub templates
  .github/ISSUE_TEMPLATE/blank.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  Makefile
Labels: ci, stdev, wip

#101 Travis for windows and linux with docker
  .travis.yml
Labels: ci, stdev, wip

#90 fixes #71 #46 - Segmentation fault when opening the Blockchain page repeteadly
  main.go
  src/coin/skycoin/main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/core/account.go
  src/core/coin.go
  src/core/main.go
  src/core/meta.go
  src/core/network.go
  src/models/blockchain/BlockchainModels.go
  src/models/blockchainModels.go
  src/models/models.go
  src/ui/Blockchain.qml
  src/ui/GeneralStackView.qml
  src/ui/main.qml
  src/util/util.go
Labels: qml_models, stdev

#113 Add dynamic configuration to wallet
  README.md
  main.go
  src/coin/skycoin/main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/wallet.go
  src/main/config.go
  src/models/config.go
  src/models/wallets.go
  src/models/walletsManager.go
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/PanelItem.qml
  src/ui/Delegates/SettingNetworkDelegate.qml
  src/ui/Delegates/SettingsDelegate.qml
  src/ui/Delegates/SettingsWalletDelegate.qml
  src/ui/GeneralStackView.qml
  src/ui/NetworkSettings.qml
  src/ui/Settings.qml
  src/ui/WalletSettings.qml
  src/ui/main.qml
Labels: config, qml_models, stdev, wallet, wip

#106 Fixes #97 Display qr on screen
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/HistoryListDelegate.qml
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Dialogs/DialogQR.qml
  src/ui/Dialogs/QRCode.qml
  src/ui/Dialogs/qqr.js
  src/ui/SubPageSendSimple.qml
  src/ui/main.qml
Labels: gui, stdev, wip

#116 Create connections pool
  main.go
  src/coin/skycoin/main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/params.go
  src/coin/skycoin/params/params.go
  src/core/network.go
Labels: config, core, stdev, wallet, wip
