Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-10, with the labels that each got.

#158 Context menus and floating labels on TextFields
  images.qrc
  resources/images/icons/clear.svg
  resources/images/icons/copy-content.svg
  resources/images/icons/cut-content.svg
  resources/images/icons/paste-content.svg
  resources/images/icons/redo.svg
  resources/images/icons/selectAll-content.svg
  resources/images/icons/undo.svg
  src/ui/ControlGenerateSeed.qml
  src/ui/Controls/+material/TextArea.qml
  src/ui/Controls/+material/TextField.qml
  src/ui/Controls/TextArea.qml
  src/ui/Controls/TextField.qml
  src/ui/CreateLoadWallet.qml
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogAboutLicense.qml
  src/ui/Dialogs/DialogAddLoadWallet.qml
  src/ui/Dialogs/DialogEditWallet.qml
  src/ui/Dialogs/DialogSelectAddressByWallet.qml
  src/ui/Dialogs/DialogSetPassword.qml
  src/ui/Dialogs/NumPadDialog.qml
  src/ui/Dialogs/RestoreBackupWordsDialog.qml
  src/ui/Dialogs/WalletCreatedDialog.qml
  src/ui/NetworkSettings.qml
  src/ui/PasswordRequester.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/SubPageSendSimple.qml
  src/ui/WalletSettings.qml
Labels: enhancement, gui

#159 Update of fix to #38 - Set a license
  src/ui/Dialogs/DialogAbout.qml
  src/ui/main.qml
Labels: bug, gui

#157 Add filter to combo boxes
  src/ui/Dialogs/DialogSelectAddressByWallet.qml
  src/ui/FilterComboBoxPopup.qml
  src/ui/SubPageSendAdvanced.qml
Labels: enhancement, gui, stdev

#149 Fixes #44 backend to manage transactions
  images.qrc
  resources/images/icons/settings.svg
  src/coin/skycoin/main.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/networking.go
  src/coin/skycoin/models/wallet.go
  src/core/main.go
  src/core/network.go
  src/core/storage.go
  src/core/wallet.go
  src/models/Outputs.go
  src/models/addressesModel.go
  src/models/config.go
  src/models/history/historyManager.go
  src/models/modelAddresses.go
  src/models/modelOutputs.go
  src/models/models.go
  src/models/modelsManager.go
  src/models/networkingManager.go
  src/models/qtransaction.go
  src/models/transactions/transactions.go
  src/models/walletsManager.go
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/HistoryFilterListAddressDelegate.qml
  src/ui/Delegates/HistoryFilterListDelegate.qml
  src/ui/Delegates/HistoryListDelegate.qml
  src/ui/Delegates/SettingNetworkDelegate.qml
  src/ui/Delegates/SettingsDelegate.qml
  src/ui/Delegates/SettingsWalletDelegate.qml
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogGetPassword.qml
  src/ui/Dialogs/DialogSelectAddressByWallet.qml
  src/ui/Dialogs/DialogSendTransaction.qml
  src/ui/GeneralStackView.qml
  src/ui/HistoryFilterList.qml
  src/ui/PageHistory.qml
  src/ui/PageSend.qml
  src/ui/PageWallets.qml
  src/ui/Settings.qml
  src/ui/SubPageSendAdvanced.qml
  src/ui/SubPageSendSimple.qml
  src/ui/TransactionDetails.qml
  src/util/util.go
Labels: skyfiber, stdev, wallet, wip

#171 Centralize WalletEnv
  src/models/models.go
  src/models/walletsManager.go
  src/ui/SubPageSendAdvanced.qml
Labels: skyfiber, stdev, wallet, wip

#175 Fix pool
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/core/network.go
Labels: skyfiber, stdev, wip

#165 Fixes #142 Configure golang-ci and run it in Travis builds
  .golangci.yml
  .travis.yml
  .travis/install-golangci-lint.sh
  Makefile
  src/coin/skycoin/main.go
  src/coin/skycoin/main_test.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/networking.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/params.go
  src/coin/skycoin/params/params.go
  src/core/network.go
  src/main/config.go
  src/models/walletsManager.go
  src/util/pluginutil.go
  src/util/util.go
Labels: stdev, wip

#173 Reduce number of operations in wallet manager
  src/models/walletsManager.go
Labels: skyfiber, stdev, wip

#153 application panics and logs
  CHANGELOG.md
  src/coin/skycoin/main_test.go
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/main_test.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/networking.go
  src/coin/skycoin/models/wallet.go
  src/core/main.go
  src/core/network.go
  src/main/config.go
  src/models/address/address.go
  src/models/addressesModel.go
  src/models/blockchainModels.go
  src/models/config.go
  src/models/history/history.go
  src/models/history/historyManager.go
  src/models/modelWallets.go
  src/models/networkingManager.go
  src/models/pending/PendingModel.go
  src/models/qtransaction.go
  src/models/wallet.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/Delegates/HistoryFilterListAddressDelegate.qml
  src/ui/Delegates/HistoryFilterListDelegate.qml
  src/ui/PageHistory.qml
  src/ui/PageSend.qml
  src/ui/Settings.qml
  src/util/logging/formatter.go
  src/util/logging/hooks.go
  src/util/logging/logger.go
  src/util/logging/logging.go
Labels: config, core, stdev, wip

#186 [main] [models] [sky] refs #143 - Unified error handling. Error constants
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/blockchain.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/main.go
  src/coin/skycoin/models/network.go
  src/coin/skycoin/models/wallet.go
  src/core/network.go
  src/errors/error.go
  src/main/config.go
  src/models/walletsManager.go
Labels: core, qml_models, skyfiber, stdev, wip
