Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-12, with the labels that each got.

#261 Fixes #256 Add converalls
  .travis.yml
  Makefile
  README.md
Labels: stdev, wip

#269 fixes #266 - Implement SCH ticker for Skycoin coin hours
  src/coin/skycoin/params/params.go
Labels: skyfiber, stdev, wip

#264 fixes #231 - Method for address verification
  src/coin/skycoin/models/account.go
  src/coin/skycoin/models/account_test.go
  src/coin/skycoin/models/cipher.go
  src/coin/skycoin/models/cipher_test.go
  src/coin/skycoin/models/coin.go
  src/coin/skycoin/models/coin_test.go
  src/coin/skycoin/models/main.go
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/models/wallet_test.go
  src/core/cipher.go
  src/core/main.go
  src/util/cipher.go
  src/util/cipher_test.go
  src/util/util.go
Labels: core, skyfiber, stdev, wip

#283 [Add coverall.io webhook to travis
  .travis.yml
Labels: ci

#281 Update addresses balance correctly
  src/models/addressesModel.go
  src/models/walletsModel.go
Labels: bug, gui, stdev, wallet

#282 Fix #278 Unable to sign transactions
  src/coin/skycoin/models/wallet.go
  src/coin/skycoin/models/wallet_test.go
Labels: sign_api, wallet

#287 Fixes #286 - Repository name updated properly in project
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: bug, ci, stdev

#288 add Spanish Translation to FiberCryptoWallet
  resources/translations/FiberCryptoWallet_es.ts
Labels: i18n

#285 Fixes #263 - Format the numbers in the ui views correctly
  src/models/blockchainModels.go
  src/models/history/historyManager.go
  src/models/walletsModel.go
Labels: gui, stdev

#291 Loading and creating wallet from main page
  src/models/addressesModel.go
  src/ui/GeneralStackView.qml
Labels: bug, gui, qml_models

#260 Fixes #135: Handle application configuration using `QSettings`
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
  main.go
  resources/images/icons/user_icon-icons.com_66546.svg
  resources/translations/FiberCryptoWallet_es.ts
  src/coin/skycoin/config/config.go
  src/coin/skycoin/main.go
  src/coin/skycoin/models/coin_test.go
  src/coin/skycoin/models/main.go
  src/coin/skycoin/models/main_test.go
  src/coin/skycoin/models/wallet_test.go
  src/core/storage.go
  src/data/addressbook.go
  src/data/contact.go
  src/data/dataUtil.go
  src/data/data_test.go
  src/data/database.go
  src/data/database_test.go
  src/main/config.go
  src/models/addressBook/address.go
  src/models/addressBook/contacts.go
  src/models/addressesModel.go
  src/models/blockchainModels.go
  src/models/config.go
  src/models/history/historyManager.go
  src/models/modelWallets.go
  src/models/models.go
  src/models/walletsManager.go
  src/models/walletsModel.go
  src/ui/AddressBook.qml
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/AddressListDelegate.qml
  src/ui/Delegates/ContactDelegate.qml
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/SectionDelegate.qml
  src/ui/Dialogs/DialogAddContact.qml
  src/ui/Dialogs/DialogSelectAddressByAddressBook.qml
  src/ui/Dialogs/DialogSelectSecType.qml
  src/ui/Dialogs/DialogShowContact.qml
  src/ui/GeneralStackView.qml
  src/ui/Settings.qml
  src/ui/SubPageSendSimple.qml
  src/ui/main.qml
  src/util/cipher_test.go
Labels: config, stdev, wip

#292 Disable Windows tests in travis
  .travis.yml
  .travis/install-qt-win.sh
  .travis/qt-installer-windows.qs
  .travis/report-progress.sh
  Makefile
Labels: ci

#303 Fixes #302 - Solve outputs bug
  src/models/modelWallets.go
Labels: bug, gui, stdev, wip

#299 Update vendor and changelog after merging address book
  CHANGELOG.md
  Gopkg.lock
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
Labels: ci
