Repository fibercrypto/fibercryptowallet, pull requests merged in 2019-07, with the labels that each got.

#70 Fixes #67 fix transitions in the general stack view
  images.qrc
  resources/images/icons/appIcon.png
  resources/images/icons/blockchain.svg
  resources/images/icons/networking.svg
  resources/images/icons/outputs.svg
  resources/images/icons/qt_logo_green_rgb_256x256.png
  src/ui/Blockchain.qml
  src/ui/CustomHeader.qml
  src/ui/CustomMenuBar.qml
  src/ui/CustomMenuItem.qml
  src/ui/GeneralStackView.qml
  src/ui/Networking.qml
  src/ui/main.qml
Labels: gui, stdev, wip

#75 stdevCrow Fix the layout of all dialogs
  src/ui/Dialogs/DialogSendTransaction.qml
  src/ui/Dialogs/DialogTransactionDetails.qml
  src/ui/Dialogs/DialogUnconfiguredWallet.qml
  src/ui/Dialogs/MsgDialog.qml
  src/ui/Dialogs/NumPadDialog.qml
  src/ui/Dialogs/RestoreBackupWordsDialog.qml
  src/ui/Dialogs/SecureWalletDialog.qml
  src/ui/Dialogs/WalletCreatedDialog.qml
  src/ui/PageHistory.qml
  src/ui/PageSend.qml
  src/ui/TransactionDetails.qml
  src/ui/main.qml
Labels: bug, gui, stdev

#82 Fixes #76 Add UI to edit wallets
  qml.qrc
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogEditWallet.qml
Labels: gui, stdev, wip

#84 Fixes issue #24 - An UI that shows the outputs
  qml.qrc
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/OutputsListDelegate.qml
  src/ui/GeneralStackView.qml
  src/ui/Outputs.qml
  src/ui/main.qml
Labels: enhancement, gui, stdev, wip

#83 Fixes #77 - Add UI to add addresses
  qml.qrc
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogAddAddresses.qml
Labels: gui, stdev, wip

#85 Fix wallet edditing
  src/ui/Delegates/WalletListAddressDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
Labels: bug, gui, stdev, wip

#87 Fix issue #23 - An UI that shows the pending transactions
  images.qrc
  resources/images/icons/pending-transactions.svg
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/PendingTransactionsDelegate.qml
  src/ui/GeneralStackView.qml
  src/ui/PendingTransactions.qml
  src/ui/main.qml
Labels: enhancement, gui, stdev, wip

#91 Fixes issue #80 - Add an UI to add wallets to the wallets model
  qml.qrc
  src/ui/ControlGenerateSeed.qml
  src/ui/CreateLoadWallet.qml
  src/ui/Dialogs/DialogAddLoadWallet.qml
  src/ui/PageSend.qml
  src/ui/PageWallets.qml
Labels: enhancement, gui, stdev, wip

#92 Fixes issue #23: An UI that shows the pending transactions
  src/ui/Delegates/PendingTransactionsDelegate.qml
  src/ui/PendingTransactions.qml
Labels: bug, gui, stdev, wip

#68 Add travis config to project
  .gitignore
  .travis.yml
  .travis/install-linux.sh
  .travis/install-os.sh
  Makefile
  src/util/pluginutil.go
Labels: ci, stdev, wip

#93 Add notifications to travis
  .travis.yml
Labels: ci, stdev, wip

#94 Fixes issue #24 - An UI that shows the outputs
  qml.qrc
  src/ui/Delegates/OutputsListAddressDelegate.qml
  src/ui/Delegates/OutputsListAddressOutputDelegate.qml
  src/ui/Delegates/OutputsListDelegate.qml
  src/ui/Outputs.qml
Labels: bug, gui, stdev, wip
