Repository fibercrypto/fibercryptowallet, pull requests merged in 2020-03, with the labels that each got.

#354 Improve code quality for hw signer
  src/coin/mocks/PersistibleSet.go
  src/coin/skycoin/models/wallet.go
  src/core/wallet.go
  src/models/walletsManager.go
  src/models/walletsModel.go
Labels: bug, core, enhancement, skywallet, wallet-hw

#355 Set the size of the splash dialog from the implicit size
  src/ui/splash.qml
Labels: bug, gui

#345 Add section to readme for release steps
  CHANGELOG.md
  README.md
  qml.qrc
  src/ui/Delegates/AddressListDelegate.qml
  src/ui/Delegates/ContactDelegate.qml
  src/ui/HistoryFilterList.qml
Labels: ci
