Repository fibercrypto/fibercryptowallet, pull requests merged in 2020-01, with the labels that each got.

#300 Fixes #286 - Repository name updated properly in project
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: bug, ci, stdev

#307 Fixes #263 - Format the numbers in the ui views correctly
  src/models/blockchainModels.go
  src/models/history/historyManager.go
  src/models/walletsModel.go
Labels: gui, stdev

#308 Re-added addressBook
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  main.go
  resources/images/icons/user_icon-icons.com_66546.svg
  src/core/storage.go
  src/data/addressbook.go
  src/data/contact.go
  src/data/data_test.go
  src/data/database.go
  src/models/addressBook/address.go
  src/models/addressBook/contacts.go
  src/models/addressesModel.go
  src/ui/AddressBook.qml
  src/ui/CustomMenuBar.qml
  src/ui/Delegates/AddressListDelegate.qml
  src/ui/Delegates/ContactDelegate.qml
  src/ui/Delegates/DestinationListDelegate.qml
  src/ui/Delegates/SectionDelegate.qml
  src/ui/Dialogs/DialogAddContact.qml
  src/ui/Dialogs/DialogSelectAddressByAddressBook.qml
  src/ui/Dialogs/DialogSelectSecType.qml
  src/ui/Dialogs/DialogShowContact.qml
  src/ui/GeneralStackView.qml
  src/ui/Settings.qml
  src/ui/SubPageSendSimple.qml
  src/ui/main.qml
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
Labels: addressbook

#301 Fixes 199 Configurable data refresh timeout
  src/coin/skycoin/config/config.go
  src/coin/skycoin/models/main.go
  src/main/config.go
  src/ui/Settings.qml
Labels: config

#310 Fix scrolling issues in both outputs list views
  src/ui/TransactionDetails.qml
Labels: bug, gui

#311 Fix scrolling issues v2 AND Errors handling in the QML Engine
  main.go
  src/ui/Delegates/HistoryFilterListDelegate.qml
  src/ui/Delegates/HistoryListDelegate.qml
  src/ui/Delegates/WalletListDelegate.qml
  src/ui/Dialogs/DialogTransactionDetails.qml
  src/ui/HistoryFilterList.qml
  src/ui/PageHistory.qml
  src/ui/PageSend.qml
  src/ui/TransactionDetails.qml
Labels: bug, gui

#314 Add QSetting to the AddressBook
  src/models/addressBook/contacts.go
Labels: addressbook

#312 [vendor] Update vendor
  Gopkg.lock
Labels: config, stdev

#316 Drop widgets support
  main.go
  qml.qrc
  src/ui/PageWallets.qml
  src/ui/splash.qml
Labels: enhancement, gui

#317 Fixes #298 - Configuration of app's logger
  .gitignore
  src/coin/skycoin/config/config.go
  src/coin/skycoin/main.go
  src/main/config.go
  src/models/config.go
  src/ui/Settings.qml
  src/ui/TransactionDetails.qml
  src/util/logging/logger.go
  src/util/logging/logging.go
  src/util/logging/logging_test.go
Labels: config, stdev, wip
